# Generated by Django 5.1.1 on 2024-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_mail_client_alter_mail_end_sending_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='send',
            options={'ordering': ['sending_status'], 'verbose_name': 'Управление рассылкой', 'verbose_name_plural': 'Управление рассылками'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('Завершен', 'статус: Завершен'), ('Создан', 'статус: Создан'), ('Запущен', 'статус: Запущен')], default='Запущен', max_length=10, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='send',
            name='sending_status',
            field=models.CharField(choices=[('Успешно', 'статус: Успешно'), ('Не успешно', 'статус: Не успешно')], default='Успешно', max_length=10, verbose_name='Статус попытки рассылки'),
        ),
    ]
