# Generated by Django 4.2.2 on 2024-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_client_owner_mail_owner_sms_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'permissions': [('can_unblocking_client', 'can unblocking client'), ('can_disabling_mailings', 'can disabling mailings')], 'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['status'], 'permissions': [('can_unblocking_mailing', 'can unblocking mailing'), ('can_disabling_mailings', 'can disabling mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'permissions': [('can_unblocking_sms', 'can unblocking sms'), ('can_disabling_mailings', 'can disabling mailings')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='client',
            name='blocking_client',
            field=models.BooleanField(default=False, verbose_name='Блокировка получателя рассылки'),
        ),
        migrations.AddField(
            model_name='client',
            name='disabling_mailings',
            field=models.BooleanField(default=False, verbose_name='Рассылка отключена'),
        ),
        migrations.AddField(
            model_name='mail',
            name='blocking_mailing',
            field=models.BooleanField(default=False, verbose_name='Блокировка рассылки'),
        ),
        migrations.AddField(
            model_name='mail',
            name='disabling_mailings',
            field=models.BooleanField(default=False, verbose_name='Рассылка отключена'),
        ),
        migrations.AddField(
            model_name='sms',
            name='blocking_sms',
            field=models.BooleanField(default=False, verbose_name='Блокировка сообщения'),
        ),
        migrations.AddField(
            model_name='sms',
            name='disabling_mailings',
            field=models.BooleanField(default=False, verbose_name='Рассылка отключена'),
        ),
    ]
