# Generated by Django 4.2.2 on 2024-11-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_client_options_alter_mail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time_mail', models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')),
                ('status', models.CharField(max_length=50, verbose_name='Статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ сервера')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.mail', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
