# Generated by Django 4.2.2 on 2024-11-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0009_log"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
