# Generated by Django 4.2.2 on 2024-11-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0010_delete_log"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mail",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("set_is_active", "set is active"),
                    ("can_disable_mailing", "can disable mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
