# Generated by Django 4.2.2 on 2024-11-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0011_alter_mail_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_blocking_client", "Может блокировать получателя")
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mail",
            options={
                "ordering": ["status"],
                "permissions": [("set_is_active", "set is active")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="sms",
            options={
                "permissions": [("can_blocking_sms", "Может блокировать сообщение")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AddField(
            model_name="sms",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активность"),
        ),
    ]
