# Generated by Django 4.2.2 on 2024-11-21 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message", "0012_alter_client_options_alter_mail_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="send",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="укажите Владельца рассылки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец рассылки",
            ),
        ),
    ]
