# Generated by Django 4.2.2 on 2024-11-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0013_send_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="send",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="send",
                to="message.mail",
                verbose_name="Статус рассылки",
            ),
        ),
    ]
