# Generated by Django 4.2.2 on 2024-11-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0014_alter_send_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="send",
            options={
                "ordering": ["data", "sending_status"],
                "verbose_name": "Управление рассылкой",
                "verbose_name_plural": "Управление рассылками",
            },
        ),
    ]
